version: '3'

services:
  web:
    build: .
    command: python app.py
    ports:
      - '5000:5000'
    volumes:
      - .:/code
    links:
      - redis
  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'